apiVersion: v1alpha2
kind: Configuration
metadata:
  name: loadtesting
specs:
  metricsEnabled: true
  webhooks:
    - name: loadtesting
      entrypointUrl: /loadtesting
      security:
        type: custom
        specs:
          condition: |
            {{ eq (.Request.Header.Peek "X-Hook-Secret" | toString) "test" }}
