apiVersion: v1alpha1
observability:
  metricsEnabled: true
specs:
- name: exampleHook
  entrypointUrl: /webhooks/example
  security:
  - header:
      inputs:
      - name: headerName
        value: X-Hook-Secret
  - compare:
      inputs:
      - name: first
        value: '{{ .Outputs.header.value }}'
      - name: second
        valueFrom:
          envRef: SECRET_TOKEN
  storage:
  - type: redis
    specs:
      host: redis
      port: '6379'
      database: 0
      password:
        valueFrom:
          envRef: REDIS_PASSWORD
      key: example-webhook
  response:
    formatting:
      templateString: '{ "status": "ok" }'
    httpCode: 200
    contentType: application/json