apiVersion: v1alpha1
specs:
- name: exampleHook
  entrypointUrl: /webhooks/example
  security:
  - getHeader:
      name: X-Hook-Secret
  - compareWithStaticValue:
      value: 'test'
      values: ['foo', 'bar']
  storage:
  - type: redis
    specs:
      host: redis
      port: 6379
      database: 0
      channel: example-webhook