apiVersion: v1alpha1
specs:
- name: exampleHook
  entrypointUrl: /webhooks/example
  security:
  - getHeader:
      name: X-Hook-Secret
  - compareWithStaticValue:
      value: 'test'
      values: ['foo', 'bar']