---
name: Tests 🚀
on:
  push:
    branches:
      - main
    pull_request:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./...

      - name: Bench
        run: go test -v -bench ./...
