name: Tests 🛠️
on: 
  push:
    paths-ignore:
    - .github/FUNDING.yml
    - .github/issue_template/*
    - config/*
    - .gitignore
    - CODE_OF_CONDUCT.md
    - CODEOWNERS
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - pull_request_template.md
permissions:
  contents: read
jobs:
  applications-test-units:
    name: "GoLang test units"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        check-latest: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
    - name: Run Unit tests
      run: |
        go test ./... -coverprofile coverage.out -covermode count
        go tool cover -func coverage.out
    - name: Quality Gate - Test coverage shall be above threshold
      env:
          TESTCOVERAGE_THRESHOLD: 80
      run: |
        echo "Quality Gate: checking test coverage is above threshold ..."
        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
        totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "Current test coverage : $totalCoverage %"
        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "OK"
        else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
        fi
    - name: Run Go Build
      run: |
        go build -o /tmp/applications-test-units